/**:
  ros__parameters:
    startup_px4_usb_quirk: false

# --- System plugins ---

# System status
/**/sys:
  ros__parameters:
    min_voltage: [10.0]   # diagnostics min voltage, use a vector i.e. [16.2, 16.0] for multiple batteries, up-to 10 are supported
                          # to achieve the same on a ROS launch file do: <rosparam param="sys/min_voltage">[16.2, 16.0]</rosparam>
    disable_diag: false   # disable all sys_status diagnostics, except heartbeat
    heartbeat_rate: 1.0   # send heartbeat rate in Hertz
    conn_timeout: 10.0    # heartbeat timeout in seconds

# System time
/**/time:
  ros__parameters:
    time_ref_source: "fcu"    # time_reference source
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6   # timesync averaging factor
    timesync_rate: 100.0      # TIMESYNC rate in Hertz (feature disabled if 0.0)
    system_time_rate: 1.0     # send system time to FCU rate in Hertz (disabled if 0.0)

# --- Mavros plugins ---

# Command
/**/cmd:
  ros__parameters:
    use_comp_id_system_control: false   # quirk for some old FCUs

# Global position
/**/global_position:
  ros__parameters:
    frame_id: "world"                   # origin frame
    child_frame_id: "AGENTID/body"      # body-fixed frame
    rot_covariance: 99999.0             # covariance for attitude?
    gps_uere: 1.0                       # User Equivalent Range Error (UERE) of GPS sensor (m)
    use_relative_alt: true              # use relative altitude for local coordinates
    tf.send: true                       # send TF?
    tf.frame_id: "world"                # TF frame_id
    tf.global_frame_id: "earth"         # TF earth frame_id
    tf.child_frame_id: "AGENTID/body"   # TF child_frame_id

# Local position
/**/local_position:
  ros__parameters:
    frame_id: "AGENTID/local"
    tf.send: false
    tf.frame_id: "AGENTID/local"
    tf.child_frame_id: "AGENTID/body"

# Setpoint position
/**/setpoint_position:
  ros__parameters:
    tf.listen: true                     # enable tf listener (enable topic subscribers)
    tf.frame_id: "world"
    tf.child_frame_id: "AGENTID/body"
    tf.rate_limit: 50.0
    mav_frame: LOCAL_NED