/**:
  ros__parameters:
    # Takeoff and landing altitude (m)
    takeoff_altitude: 3.0
    landing_altitude: 0.5

/**/drone_control_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

    # Control mode (0: position, 1: velocity)
    control_mode: 0