/**/simulation_gui_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0

/**/target_state_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0

/**/target_control_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0
    # Highlight targets
    highlight_targets: false
    # Highlight clusters
    highlight_clusters: false

/**/agent_simulation_bridge_node:
  ros__parameters:
    # Bridge update rate (Hz)
    bridge_update_rate: 20.0