/**:
  ros__parameters:
    # Simulation settings
    simulation:
      framework: AirSim
      clock_speed: 1.0    # Clock speed multiplier (1.0 = real-time)
      quality_preset: 1

    # Path settings
    path:
      config_spreadsheet_path: "/home/testuser/FlyChams-ROS2/src/flychams_common/config/Configuration-Multi-Agent.xlsx"
      mission_settings_path: "/home/testuser/FlyChams-ROS2/src/flychams_common/config/generated/mission.yaml"
      airsim_settings_path: "/home/testuser/FlyChams-ROS2/src/flychams_common/config/generated/airsim.json"
      foxglove_layout_path: "/home/testuser/FlyChams-ROS2/src/flychams_common/config/generated/flychams.json"
      trajectory_root: "/home/testuser/FlyChams-ROS2/src/flychams_common/config/trajectories"
      
    # GUI settings
    gui:
      # Scenario view settings
      scenario_view_id: "SCENARIOVIEW"
      scenario_camera_id: "SCENARIOCAM"
      scenario_camera_position: [-80.0, -80.0, 70.0]       # [x, y, z]
      scenario_camera_orientation: [0.0, 15.0, 45.0]  # [roll, pitch, yaw]
      scenario_camera_resolution: [1280, 720]           # [width, height]
      # Agent view settings
      agent_view_id: "AGENTVIEW"
      agent_camera_id: "AGENTCAM"
      agent_camera_position: [-1.5, -1.5, 1.0]        # [x, y, z]
      agent_camera_orientation: [0.0, 33.33, 45.0]   # [roll, pitch, yaw]
      agent_camera_resolution: [854, 480]               # [width, height]
      # Payload view settings
      payload_view_id: "PAYLOADVIEW"
      payload_camera_id: "PAYLOADCAM"
      payload_camera_position: [-0.7, -0.7, -0.5]        # [x, y, z]
      payload_camera_orientation: [0.0, 0.0, 45.0]   # [roll, pitch, yaw]
      payload_camera_resolution: [854, 480]             # [width, height]