/**:
  ros__parameters:
    # Coordinator topics
    coordinator_topics:
      registration: "/flychams/coordinator/registration" # Registration.msg (custom)
      mission_status: "/flychams/coordinator/mission_status" # MissionStatus.msg (custom)
      fleet_status: "/flychams/coordinator/fleet_status" # FleetStatus.msg (custom)
      global_origin: "/flychams/coordinator/global_origin" # GeoPointStamped.msg
      target_position: "/flychams/coordinator/TARGETID/position" # PointStamped.msg
      cluster_assignment: "/flychams/coordinator/CLUSTERID/assignment" # ClusterAssignment.msg (custom)
      cluster_geometry: "/flychams/coordinator/CLUSTERID/geometry" # ClusterGeometry.msg (custom)      

    # Agent topics
    agent_topics:
      agent_status: "/flychams/agent/AGENTID/status" # AgentStatus.msg (custom)
      agent_global_position: "/flychams/agent/AGENTID/global_position" # PointStamped.msg
      agent_local_position: "/flychams/agent/AGENTID/local_position" # PointStamped.msg
      agent_assignment: "/flychams/agent/AGENTID/assignment" # AgentAssignment.msg (custom)
      agent_clusters: "/flychams/agent/AGENTID/clusters" # AgentClusters.msg (custom)
      agent_position_setpoint: "/flychams/agent/AGENTID/position_setpoint" # PointStamped.msg
      observation_setpoints: "/flychams/agent/AGENTID/observation_setpoints" # ObservationSetpoints.msg (custom)
      
    # Operator topics
    operator_topics:
      image: "/flychams/operator/ELEMENTID/VIEWID/image" # Image.msg
      annotations: "/flychams/operator/ELEMENTID/VIEWID/annotations" # foxglove_msgs/ImageAnnotations
      scene: "/flychams/operator/ELEMENTID/scene" # foxglove_msgs/SceneUpdate
      start_mission: "/flychams/operator/start_mission" # std_msgs/Bool
      pause_mission: "/flychams/operator/pause_mission" # std_msgs/Bool
      abort_mission: "/flychams/operator/abort_mission" # std_msgs/Bool
      arm_all: "/flychams/operator/arm_all" # std_msgs/Bool
      land_all: "/flychams/operator/land_all" # std_msgs/Bool
      return_home: "/flychams/operator/return_home" # std_msgs/Bool
      mission_metrics: "/flychams/operator/mission_metrics" # MissionMetrics.msg (custom)
      agent_metrics: "/flychams/operator/AGENTID/agent_metrics" # AgentMetrics.msg (custom)
      target_metrics: "/flychams/operator/TARGETID/target_metrics" # TargetMetrics.msg (custom)
      cluster_metrics: "/flychams/operator/CLUSTERID/cluster_metrics" # ClusterMetrics.msg (custom)