/**/fleet_state_node:
  ros__parameters:
    # Update rate (Hz)
    fleet_state_rate: 1.0

/**/element_registrator_node:
  ros__parameters:
    # Update rate (Hz)
    registration_rate: 1.0

/**/mission_state_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 1.0
    # Auto-start mission when fleet is ready
    mission_autostart: true

/**/fleet_state_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 1.0

/**/target_clustering_node:
  ros__parameters:
    # Update rate (Hz)
    clustering_rate: 3.33

    # Persistence parameters
    persistence:
      ini_bonding_coef: 1.0           # Initial bonding coefficient
      max_bonding_coef: 1.0           # Maximum bonding coefficient
      bonding_coef_time_to_max: 100.0 # Time from 0 to max bonding coefficient (s)
      max_hysteresis_ratio: 1.6       # Maximum hysteresis ratio
      min_hysteresis_ratio: 0.8       # Minimum hysteresis ratio

/**/cluster_analysis_node:
  ros__parameters:
    # Update rate (Hz)
    analysis_rate: 20.0
    
    # Enclosing circle parameters
    enclosing_circle:
      min_circle_radius: 0.3
      margin_circle_radius: 2.5

/**/agent_assignment_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0
    # Minimum inter-solve rate (Hz)
    min_assignment_rate: 1.0

    # Assignment parameters
    assignment:
      # Assignment solver mode
      # 0: GREEDY, 1: EXHAUSTIVE_SEARCH, 2: BRANCH_AND_BOUND
      solver_mode: 2
      # Optimization weights
      observation_weight: 1.0
      distance_weight: 10.0
      switch_weight: 5000.0

    # Positioning parameters
    positioning:
      # Positioning solver mode 
      # 0: ELLIPSOID_METHOD, 1: NELDER_MEAD_NLOPT, 2: NESTEROV_ALGORITHM, 
      # 3: L_BFGS_NLOPT, 4: PSO_ALGORITHM, 5: ALC_PSO_ALGORITHM, 6: CMA_ES_ALGORITHM
      solver_mode: 3
      # Solver parameters
      eps: 1.0e-1
      convergence_tolerance: 1.0e-5
      max_iterations: 1000
      # PSO parameters
      num_particles: 50
      w_max: 0.4
      w_min: 0.1
      c1: 1.0
      c2: 1.0
      stagnation_limit: 5
      # ALC-PSO parameters
      max_lifespan: 60
      num_challenger_tests: 10
      # Nesterov parameters
      lipschitz_constant: 0.0
      # Cost function weights
      cost_weights:
        tau0: 1.0
        tau1: 2.0
        tau2: 10.0
        sigma0: 1.0
        sigma1: 2.0
        sigma2: 10.0
        mu1: 1.0
        mu2: 1.0