FROM ros:humble-ros-base

# --- Setup ROS2 Humble Packages ---
RUN apt-get update && \
    apt-get install -y \
    ros-$ROS_DISTRO-tf2-sensor-msgs \
    ros-$ROS_DISTRO-tf2-geometry-msgs \
    ros-$ROS_DISTRO-mavros* \
    ros-$ROS_DISTRO-vision-opencv \
    ros-$ROS_DISTRO-image-transport \
    libyaml-cpp-dev \
    ros-$ROS_DISTRO-pcl-ros \
    ros-$ROS_DISTRO-pcl-conversions \
    && rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Install GeographicLib datasets for mavros
RUN wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh && \
    chmod +x install_geographiclib_datasets.sh && \
    ./install_geographiclib_datasets.sh && \
    rm install_geographiclib_datasets.sh

# --- Setup Ultralytics ---
RUN apt-get update && apt-get install -y python3-pip && \
    pip3 install ultralytics lapx && \
    rm -rf /var/lib/apt/lists/*

# --- Setup GStreamer ---
RUN apt-get update && \ 
    apt-get install -y \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    gstreamer1.0-alsa \
    gstreamer1.0-gl \
    && rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Create a non-root user with sudo access
ARG USER_NAME=testuser
ENV USER_NAME=${USER_NAME}
RUN adduser --disabled-password --gecos '' $USER_NAME \
    && adduser $USER_NAME sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Ensure the user owns their home directory
RUN chown -R $USER_NAME:$USER_NAME /home/$USER_NAME

# Automatically source ROS2 environment for the new user
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USER_NAME/.bashrc

# Switch to the non-root user
USER $USER_NAME
WORKDIR /home/${USER_NAME}