# Node launch configuration
# Set to [enable, log_level]
# Enable: true launches the node, false does not
# Log levels: debug, info, warn, error, fatal

# ------------------- GLOBAL SETUP NODES -------------------
# AirSim node
airsim: [true, 'error']
# Registrator node
registrator: [true, 'info']

# ------------------- GLOBAL RUN NODES -------------------
# Perception nodes
target_clustering: [false, 'error']
cluster_analysis: [false, 'error']
# Coordination nodes
agent_assignment: [false, 'error']
agent_analysis: [false, 'error']
# Simulation nodes
gui_manager: [true, 'error']
metrics_factory: [false, 'error']
marker_factory: [false, 'error']
target_state: [false, 'error']
target_control: [false, 'error']
# Recording nodes
airsim_record_camera: [false, 'error']

# ------------------- AGENT SETUP NODES -------------------
# MavROS node
mavros: [true, 'info']

# ------------------- AGENT RUN NODES -------------------
# Control nodes
drone_state: [false, 'error']
drone_control: [false, 'error']
camera_control: [false, 'error']
# Coordination nodes
agent_positioning: [false, 'error']
agent_tracking: [false, 'error']