/**:
  ros__parameters:
    # Global topics
    global_topics:
      registration: "/flychams/bringup/registration"                          # Registration.msg (custom)
      global_origin: "/flychams/bringup/global_origin"                        # GeoPointStamped.msg
      metrics: "/flychams/dashboard/global/metrics"                           # GlobalMetrics.msg (custom)
    # Agent topics
    agent_topics:
      status: "/flychams/control/AGENTID/status"                              # AgentStatus.msg (custom)
      local_position: "/flychams/control/AGENTID/local/position"              # PointStamped.msg
      global_position: "/flychams/control/AGENTID/global/position"            # PointStamped.msg
      assignment: "/flychams/coordination/AGENTID/assignment"                 # AgentAssignment.msg (custom)
      clusters: "/flychams/coordination/AGENTID/clusters"                     # AgentClusters.msg (custom)
      position_setpoint: "/flychams/coordination/AGENTID/setpoint/position"   # PointStamped.msg
      optimization_duration: "/flychams/coordination/AGENTID/optimization_duration" # Float32.msg
      observation_setpoints: "/flychams/coordination/AGENTID/setpoint/observation"  # AgentObservationSetpoints.msg (custom)
      metrics: "/flychams/dashboard/AGENTID/metrics"                          # AgentMetrics.msg (custom)
      markers: "/flychams/dashboard/AGENTID/markers"                          # MarkerArray.msg
    # Target topics
    target_topics:
      true_position: "/flychams/targets/TARGETID/true_position"               # PointStamped.msg
      est_position: "/flychams/perception/TARGETID/est_position"              # PointStamped.msg
      metrics: "/flychams/dashboard/TARGETID/metrics"                         # TargetMetrics.msg (custom)
      markers: "/flychams/dashboard/TARGETID/markers"                         # MarkerArray.msg
    # Cluster topics
    cluster_topics:
      assignment: "/flychams/perception/CLUSTERID/assignment"                 # ClusterAssignment.msg (custom)
      geometry: "/flychams/perception/CLUSTERID/geometry"                     # ClusterGeometry.msg (custom)
      metrics: "/flychams/dashboard/CLUSTERID/metrics"                        # ClusterMetrics.msg (custom)
      markers: "/flychams/dashboard/CLUSTERID/markers"                        # MarkerArray.msg
    # GUI topics
    gui_topics:
      setpoints: "/flychams/simulation/AGENTID/setpoint/gui"                  # GuiSetpoints.msg (custom)