# Mission configuration file
# Generated automatically from configuration spreadsheet
# Mission ID: MISSION01
# Mission Name: Single-Agent Test (Multi-Window)

/**:
  ros__parameters:
    mission:
      id: MISSION01
      name: "Single-Agent Test (Multi-Window)"
      environment_id: ENVIRONMENT00
      target_group_id: GROUP02
      agent_team_id: TEAM01
      horizontal_constraint:
        min: -150.000
        max: 150.000
      vertical_constraint:
        min: 30.000
        max: 150.000
      autopilot: 2
      start_date:
        year: 2024
        month: 12
        day: 13
      start_hour:
        hours: 16
        minutes: 30
        seconds: 0
    environment:
      id: ENVIRONMENT00
      name: "Operational Conditions O1"
      geopoint:
        latitude: 35.986557
        longitude: -5.893011
        altitude: 0.000000
      wind_vel:
        x: 3.000
        y: 1.500
        z: 0.000
    targets:
      id_list: ["TARGET02COUNT00", "TARGET02COUNT01", "TARGET02COUNT02", "TARGET02COUNT03", "TARGET02COUNT04", "TARGET02COUNT05", "TARGET02COUNT06", "TARGET02COUNT07"]
      TARGET02COUNT00:
        id: TARGET02COUNT00
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 0
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT01:
        id: TARGET02COUNT01
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 1
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT02:
        id: TARGET02COUNT02
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 2
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT03:
        id: TARGET02COUNT03
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 3
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT04:
        id: TARGET02COUNT04
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 4
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT05:
        id: TARGET02COUNT05
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 5
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT06:
        id: TARGET02COUNT06
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 6
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
      TARGET02COUNT07:
        id: TARGET02COUNT07
        name: "Target Configuration L3"
        target_group_id: GROUP02
        target_index: 7
        type: 3
        count: 8
        priority: 3
        trajectory_folder: "TargetConfigurationL3"
    agents:
      id_list: ["AGENT01"]
      AGENT01:
        id: AGENT01
        name: "Multi-Window Agent (Single)"
        agent_team_id: TEAM01
        tracking_id: TRACKING01
        drone_id: DRONE00
        position:
          x: 10.000
          y: -2.500
          z: 0.000
        orientation:
          roll: 0.000000
          pitch: 0.000000
          yaw: 0.000000
        safety_radius: 3.000
        max_altitude: 300.000
        battery_capacity: 12000.000
        tracking:
          id: TRACKING01
          name: "Multi-Window Tracking (Single)"
          observation_set_id: SET01
          min_target_size: 0.200
          max_target_size: 0.900
          ref_target_size: 0.800
          multi_cameras:
            ids: ["MULTICAMERA05"]
            MULTICAMERA05:
              id: MULTICAMERA05
              name: "Central Head Multi-Window (Single)"
              observation_set_id: SET01
              camera_id: CAM04
              gimbal_id: GIM00
              role: 1
              position:
                x: 0.000
                y: 0.000
                z: -0.150
              orientation:
                roll: 0.000000
                pitch: 1.570796
                yaw: 1.570796
              min_focal: 0.003000
              max_focal: 0.003000
              ref_focal: 0.003000
              camera:
                id: CAM04
                name: "Operational Conditions O1 (ultra-high-resolution camera)"
                type: 1
                resolution:
                  width: 7680
                  height: 4320
                sensor_size:
                  width: 0.013200
                  height: 0.007425
                distortion:
                  K1: -0.030000
                  K2: 0.002000
                  K3: 0.000000
                  P1: 0.000500
                  P2: -0.000400
                enable_sensor_noise: true
                sensor_noise:
                  rand_contrib: 0.001000
                  rand_size: 100.000000
                  rand_speed: 50000.000000
                weight: 0.800
                idle_power: 3.000
                active_power: 6.000
              gimbal:
                id: GIM00
                name: "Default Gimbal"
                enable_roll: true
                roll:
                  min_angle: -20.000000
                  max_angle: 20.000000
                  max_speed: 180.000000
                enable_pitch: true
                pitch:
                  min_angle: -40.000000
                  max_angle: 130.000000
                  max_speed: 180.000000
                enable_yaw: true
                yaw:
                  min_angle: -320.000000
                  max_angle: 320.000000
                  max_speed: 270.000000
                weight: 0.400
                idle_power: 5.000
                active_power: 15.000
          multi_windows:
            ids: ["MULTIWINDOW00", "MULTIWINDOW01", "MULTIWINDOW02", "MULTIWINDOW03"]
            MULTIWINDOW00:
              id: MULTIWINDOW00
              name: "Tracking Window 1 Multi-Window (Single)"
              observation_set_id: SET01
              resolution:
                width: 480
                height: 270
              min_lambda: 0.167
              max_lambda: 1.000
              ref_lambda: 0.583
            MULTIWINDOW01:
              id: MULTIWINDOW01
              name: "Tracking Window 2 Multi-Window (Single)"
              observation_set_id: SET01
              resolution:
                width: 480
                height: 270
              min_lambda: 0.167
              max_lambda: 1.000
              ref_lambda: 0.583
            MULTIWINDOW02:
              id: MULTIWINDOW02
              name: "Tracking Window 3 Multi-Window (Single)"
              observation_set_id: SET01
              resolution:
                width: 480
                height: 270
              min_lambda: 0.167
              max_lambda: 1.000
              ref_lambda: 0.583
            MULTIWINDOW03:
              id: MULTIWINDOW03
              name: "Tracking Window 4 Multi-Window (Single)"
              observation_set_id: SET01
              resolution:
                width: 480
                height: 270
              min_lambda: 0.167
              max_lambda: 1.000
              ref_lambda: 0.583
        drone:
          id: DRONE00
          name: "Operational Conditions O1"
          type: 2
          cruise_speed: 8.000
          max_speed: 12.000
          enable_barometer: true
          barometer:
            white_noise_sigma: 2.700000
          enable_imu: true
          imu:
            angular_white_noise_sigma: 0.300000
            velocity_white_noise_sigma: 0.240000
          enable_gps: true
          gps:
            eph_initial: 25.000000
            epv_initial: 25.000000
            eph_final: 0.100000
            epv_final: 0.100000
          enable_magnetometer: true
          magnetometer:
            white_noise_sigma: 0.005000
            white_noise_bias: 0.000000
          base_weight: 6.500
          max_payload_weight: 2.500
          hover_power: 400.000
          cruise_power: 350.000
          load_factor: 25.000
        ssh:
          hostname: "172.17.0.1"
          user: "jetson"
