/**:
  ros__parameters:
    # Takeoff and landing altitude (m)
    takeoff_altitude: 10.0
    landing_altitude: 0.5

/**/agent_frames_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 30.0

/**/agent_state_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/agent_control_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0
    # Control mode (0: position, 1: velocity)
    control_mode: 0
    # Automatically arm all agents on startup
    auto_arm: true

/**/agent_analysis_node:
  ros__parameters:
    # Update rate (Hz)
    analysis_rate: 20.0

/**/agent_positioning_node:
  ros__parameters:
    # Update rate (Hz)
    positioning_rate: 10.0
    # Positioning parameters
    positioning:
      # Positioning solver mode 
      # 0: ELLIPSOID_METHOD, 1: NELDER_MEAD_NLOPT, 2: NESTEROV_ALGORITHM, 
      # 3: L_BFGS_NLOPT, 4: PSO_ALGORITHM, 5: ALC_PSO_ALGORITHM, 6: CMA_ES_ALGORITHM
      solver_mode: 3
      # Solver parameters
      eps: 1.0e-1
      convergence_tolerance: 1.0e-5
      max_iterations: 1000
      # PSO parameters
      num_particles: 50
      w_max: 0.4
      w_min: 0.1
      c1: 1.0
      c2: 1.0
      stagnation_limit: 5
      # ALC-PSO parameters
      max_lifespan: 60
      num_challenger_tests: 10
      # Nesterov parameters
      lipschitz_constant: 0.0
      # Cost function weights
      cost_weights:
        tau0: 1.0
        tau1: 2.0
        tau2: 10.0
        sigma0: 1.0
        sigma1: 2.0
        sigma2: 10.0
        mu1: 1.0
        mu2: 1.0

/**/agent_tracking_node:
  ros__parameters:
    # Update rate (Hz)
    tracking_rate: 20.0

/**/agent_stream_node:
  ros__parameters:
    # Interface parameters
    central_view:
      width: 1280
      height: 720
    tracking_view:
      width: 640
      height: 360
    # Stream parameters
    stream_delay_ms: 500