/**/metrics_creator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0
    # Enable CPU/GPU/RAM/VRAM performance metrics collection
    enable_performance_metrics: true

/**/markers_generator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/annotations_generator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0
    # View dimensions
    central_view:
      width: 1280
      height: 720
    tracking_view:
      width: 640
      height: 360