/**/metrics_creator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/markers_generator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/annotations_generator_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0
    # View dimensions
    central_view:
      width: 854
      height: 480
    tracking_view:
      width: 427
      height: 240