/**:
  ros__parameters:
    takeoff_altitude: 3.0     # (m)
    landing_altitude: 0.5     # (m)

/**/drone_control:
  ros__parameters:
    # Drone motion parameters
    drone_control:
      update_rate: 10.0         # (Hz)
      control_mode: 0           # 0: position, 1: velocity