/**/gui_manager_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0

/**/metrics_factory_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/marker_factory_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 10.0

/**/target_state_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0

/**/target_control_node:
  ros__parameters:
    # Update rate (Hz)
    update_rate: 20.0